### ISSUE TITLE
[Organisation] Frontend Todos

### ISSUE THREAD

**Issue by mxsph** [SWTP-SS20-Kammer-2/Data-Analytics#621]
# Frontend Todos

- [x] `get_job_run_info`: Config im richtigen Format => (@davidmrt98 , #634)
- [x] Parametern abstände anpassen (Überschrift zu subParams) => (@davidmrt98, #622)
- [x] Hinweis zu TopicPanel hinzufügen => (@TimonPllkrn #574)
- [x] Pfeil vor expandable Params => (@davidmrt98, #622)
- [x] Numberinput vaidieren => (@davidmrt98 , #634)
- [x] DeleteSelection anpassen (Issue #458) => (@TimonPllkrn)
- [x] Deleteoptions in DB hinzufügen
- [x] Intervalle hinzufügen (@TimonPllkrn Issue #585)
  - mehrere Daten/zeiten (Issue #573)
- [x] JobCreate style Anpassungen
- [x] placeholder Hashtags anpassen  => (@mxsph, #623)
- [x] (React Theme Anpassen => (@TimonPllkrn #635)
  - primary, secondary
  - JobCreate und JobList style vereinen)
- [x] (`Job erstellt` anzeigen nach response)
- [x] Job erstellt Icon => (@TimonPllkrn Issue #458)
- [x] Ladekreis abbrechen => (@mxsph, #623)
- [x] (ausklappen bugs
  - Notification schließen
  - geschlossenen Job speichern)
- [x] wordcloud Größe enum => (@mxsph, #623)
- [x] LogInfos im Frontend anzeigen => (@mxsph, #629)
- [x] Feedback, wenn Job gelöscht wird => (@mxsph, #656)
- [x] **Option für "Video anhängen" hinzufügen** (@davidmrt98, #654)
- [x] Validierung für Strings (Sonderzeichen, Kommas, ...)
- [x] Tooltip bugs => (@mxsph, #653)
- [x] Job namen umbenenen Bug => (@mxsph, #653)
- [x] Wordpress title anpassen (der im Browser angezeigt wird) -> `settings` entfernen
- [x] fetch, timeout einbauen => (@mxsph, #689)
- [x] Fehler beheben: 
   ![Anmerkung 2020-08-15 124157](https://user-images.githubusercontent.com/64217916/90310742-cc591c80-def4-11ea-8955-8281ab91f4c1.png)
- [x] Wenn ein Job keine logs hat: Nachicht anpassen (da steht noch TODO 😄)
- [x] logs hintbutton text
