### ISSUE TITLE
[Organisation] Backend Todos

### ISSUE THREAD

**Issue by mxsph** [SWTP-SS20-Kammer-2/Data-Analytics#652]
# Backend Todos

- [x] Fehlermeldungen: was raised entfernen => (@mxsph,  #663)
- [x] FFmpeg Fehlermeldung verbessern => (@mxsph,  #663)
- [x] Fehlermeldungen verbessern/Korrektur lesen =>(@Tanja265, #663)
- [x] Sonnenuntergang, Sonnenaufgang `0`(null) nicht vorlesen => (@Tanja265, #686)
- [x] Memory: Wie mit veränderter Config/ Veränderter Season (vtl. option ignor_if_changed)
- [x] Alle `values[""]` oder `values.get` überprüfen das auch data.format damit aufgerufen wird => (@mxsph, #686)
- [x] transform data.get_data überprüfen ob man irgendwo noch ein datentype braucht (also z.B.: mit einem `data.get_data(..., bool)`) => (@mxsph, #686)
- [x] ignore_erros verbessern (vtl. Transformt type if key/keys exsists) => (@mxsph, #686)
- [x] video_name: leerzeichen durch - ersetzen => (@mxsph, #686)
- [x] Wetter: land einstellbar => (@mxsph, #686)
- [x] Docstring ausfräumen/Fehlende ergänzen => (@Tanja265, #700 )
- [x] Wörter normalisieren erläutern => (@Tanja265, #414)
- [x] globale presets => (@mxsph, #684)
- [x] thumbnails bei fehler löschen => (@mxsph, #686)
- [x] seqence attach: init base config => (@mxsph, #686)
- [x] Wenn Fix_names 1 ist _1 weglassen
- [x] Texte Fußball überprüfen => (@Tanja265, #700)
- [x] deep_format verbwssern => (@mxsph, #686)
- [x] append: keys support => (@mxsph, #686)
- [x] Texte für 2. Bundesliga anpassen => (@Tanja265, #700 )
- [x] Fußball-Notiz in Doku => (@Tanja265, #414)
